#!/bin/bash
docker-compose down
docker-compose rmi app-order-service app-config-server

cd /Users/lukaszmajcher/Desktop/Order-Management-App/config-server
mvn clean install
cd ..
cd /Users/lukaszmajcher/Desktop/Order-Management-App/order-service/
mvn clean install
cd ..
cd /Users/lukaszmajcher/Desktop/Order-Management-App/inventory-service/
mvn clean install

docker-compose build
docker-compose up