server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://config-server:8888"

services:
  path:
    notification-service: "http://notification-service"
    inventory-service: "http://inventory-service"
    pickup-service: "http://pickip-service"