eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1
            - TokenRelay=
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/product/**
          filters:
            - PrefixPath=/api/v1
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: oauth2-client
          uri: lb://oauth2-client
          predicates:
            - Path=/registration/**
          filters:
            - PrefixPath=/api/v1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
