#!/bin/bash

docker stop gateway-service
docker rm gateway-service
docker rmi gateway-service
mvn clean install -DskipTests
docker build -t gateway-service .
docker run --network app_network -d -p 8080:8080 --name gateway-service gateway-service