#!/bin/bash

docker exec -it config-server sh -c 'curl -X POST http://keycloak-service:8080/realms/order-management-app/protocol/openid-connect/token \
                                             -d "grant_type=client_credentials" \
                                             -d "client_id=microservice-app" \
                                             -d "client_secret=45VITVw9QlPrAJpg9HKHMnzmOz7z7uzd"'


