spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://client-db:5432/client_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

user:
  registration:
    url: /admin/realms/order-management-app/users