spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://inventory-db:5432/inventory_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver