eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
host:
  mail:
    sender: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587